---
plugin: aws_ec2
keyed_groups:
  - key: tags
    prefix: tag
regions:
  - us-west-1
filters:
  instance-state-name : running
  tag:ansible_group: routers
hostnames:
  - tag:Name
compose:
  ansible_host: public_ip_address